#web端口配置
server:
  port: 8888
dubbo:
  application:
    name: demo-provider
  protocol:
    name: dubbo #协议名称
    port: -1    #配置为-1，则会分配一个没有被占用的端口
  #注册中心配置
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    group: dev
    #此两项配置为false屏蔽dubbo启动时，会把nacos作为配置中心，自动创建多余的配置文件
    use-as-config-center: false
    use-as-metadata-center: false

